HomePage/urls.py
from django.urls import path
from . import views

app_name = 'HomePage'

urlpatterns = [
    path('signin/', views.SignIn, name='SignIn'),
    path('signup/', views.SignUp, name='SignUp'),
    path('signout/', views.SignOut, name='SignOut'),
    path('', views.Index, name='Index'),
]

ImageBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('HomePage.urls')),
    path('user/', include('UserPage.urls')),
    path('admin/', admin.site.urls),
]

UserPage/urls.py
from django.urls import path
from . import views

app_name = 'UserPage'

urlpatterns = [
    path('add-blog/', views.AddBlog, name='AddBlog'),
    path('edit-profile/', views.EditProfile, name='EditProfile'),
    path('', views.Profile, name='Profile'),
]

HomePage/models.py
from django.db import models

# Create your models here.

UserPage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    UserBio = models.TextField(max_length=100)
    ProfileImage = models.ImageField(upload_to='ProfilePics', blank=True)

    def __str__(self):
        return self.user.username

    def name(self):
        return self.user.first_name + self.user.last_name


class Blog(models.Model):

    TextContent = models.TextField()
    ImageContent = models.ImageField(upload_to='UserMedia/User')
    Date = models.DateField(auto_now_add=True)
    username = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.Title

HomePage/forms.py
from django import forms
from django.contrib.auth.models import User
from UserPage.models import UserProfile

class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')

UserPage/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserProfileForm(models.Model):
    class Meta():
        model = UserProfile
        fields = ('UserBio', 'ProfileImage')

HomePage/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm
from UserPage.models import UserProfile
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.
def Index(request):
    return render(request, 'HomePage/Index.html')


def SignIn(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('UserPage:Profile')
    else:
        form = AuthenticationForm()
    return render(request, 'HomePage/SignIn.html', {'forms':form})


def SignUp(request):
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next', ''))
            else:
                return redirect('UserPage:Profile')
    else:
        form = SignUpForm()
    return render(request, 'HomePage/SignUp.html', {'forms':form})


def SignOut(request):
    if request.method == 'POST':
        logout(request)
        return redirect('HomePage:Index')

UserPage/views.py
from django.shortcuts import render
from .models import UserProfile
from django.contrib.auth.decorators import login_required


def Profile(request):
    #user profile info
    return render(request, 'UserPage/Profile.html')


def EditProfile(request):
#     form = UserProfileForm()
#     if request.method == 'POST':
#         form = UserProfileForm(data=request.POST)
#         if form.is_valid():
#             form.save()
    return render(request, 'UserPage/EditProfile.html')


@login_required(login_url='/signin/')
def AddBlog(request):

    return render(request, 'UserPage/AddBlog.html')

templates/HomePage/Index.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">

    <blockquote>
     <p class="quotation-mark">
       “
     </p>
     <p class="quote-text">
       A professional is someone who can do his best work when he doesn't feel like it.
     </p>
    </blockquote>
    <a href="{% url 'UserPage:EditProfile' %}">Edit profile</a>
    <a href="{% url 'UserPage:AddBlog' %}">Add blog</a>
  </div>
{% endblock %}

templates/HomePage/SignIn.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>Sign In.</h1>
    <p>Edit your blogs. View your profile.</p>
  </div>
  <form action="{% url 'HomePage:SignIn' %}" method="post">
      {{forms.as_p}}
      {% csrf_token %}
      {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
      {% endif %}
      <input type="submit" class="btn btn-primary" value="Sign In">
  </form>
{% endblock %}

templates/HomePage/SignUp.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>Create an account.</h1>
    <p>Add blogs. Comment on blogs by others.</p>
  </div>
  <form method="post" action="{% url 'HomePage:SignUp' %}">
      {{forms.as_p}}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Sign Up">
  </form>
{% endblock %}

templates/UserPage/AddBlog.html
{% extends 'base.html' %}

{% block content %}
  <h1>Add a new blog.</h1>
{% endblock %}

templates/UserPage/EditProfile.html
{% extends 'base.html' %}

{% block content %}
  <form action="{% url 'HomePage:SignUp' %}" method="post" enctype="multipart/form-data">
      <!-- {{forms.as_p}} -->
      <input type="submit" class="btn btn-primary" value="Sumbit">
  </form>
{% endblock %}

templates/UserPage/Profile.html
{% extends 'base.html' %}

{% block content %}
  <a href="{% url 'UserPage:EditProfile' %}">Edit profile</a>
  <a href="{% url 'UserPage:AddBlog' %}">Add blog</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>The Image Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mainStyle.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
        <nav class="navbar navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'HomePage:Index' %}">Image Blog</a>
          <ul class="nav justify-content-end">
            <li class="nav-item"><a class="nav-link" href="/admin/">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'HomePage:Index' %}">Home</a></li>
            {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'UserPage:Profile' %}">Profile</a></li>
              <li class="nav-item">
                <form action="{% url 'HomePage:SignOut' %}" method="post">
                  {% csrf_token %}
                  <input class="nav-link" id="signOutButton" type="submit" value="Sign Out">
                </form>
              </li>
            {% else %}
               <li class="nav-item"><a class="nav-link" href="{% url 'HomePage:SignUp' %}">Sign up</a></li>
               <li class="nav-item"><a class="nav-link" href="{% url 'HomePage:SignIn' %}">Sign in</a></li>
            {% endif %}
          </ul>
        </nav>
    </header>
    <main class="container my-5">
      {%  block content %}

      {% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  </body>
</html>